auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “数学共享平台's Blog”
title: 数学共享平台
description: 数学共享平台
url:https://zhouyucheng262533.github.io/
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">数学共享平台</a>
